### ISSUE TITLE
Medaka variant_calling uses too many threads on CPU

### ISSUE THREAD

**Issue by caspargross** [nanoporetech/medaka#103]
**Describe the bug**
The `--threads` option does not limit the number of threads or cores used by the tensorflow analysis step of the model. I dont know if this is intended, but I would like to have an option to limit this in order to not overload the server.

**Logging**

```
[18:22:19 - ModelLoad] Building model with cudnn optimization: False
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-79
OMP: Info #156: KMP_AFFINITY: 80 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 2 packages x 20 cores/pkg x 2 threads/core (40 total cores)
````

**Environment (if you do not have a GPU, write No GPU):**
 - OS: [e.g. Ubuntu 16.04]
NoGPU

**Additional context**

**Comment by cjw85** [comment]
Hi @caspargross 

Medaka's CPU use may peak slightly above the specified `-t` or `--threads` option due to some threads being used for IO and data preparation.

From your log I am guessing that you are using a conda installation (the `OMP: Info` messages would not be appearing in other situations). I just created a conda install and set `-t 1` for `medaka_variant` and saw ~900% CPU use. With a from source build (and dependencies from pypi) I see only 100% usage as expected.

With the conda package I believe you will need to additionally export an environment variable to limit threading within the math libraries: `OMP_NUM_THREADS=1`. When I do this I see closer to 100% and 200% CPU usage for `-t 1` and `-t 2` respectively.

**Comment by caspargross** [comment]
Thank you,  I was using the conda installation. This information is very helpful and solves my issue.
