### ISSUE TITLE
Any plan for tensorflow 2.0?

### ISSUE THREAD

**Issue by alartin** [nanoporetech/medaka#107]
Since tensorflow 2 is out and it is much more user friendly with high order keras api. I just wonder if there is any plan to upgrade to tensorflow 2 for medaka? Thanks in advance.

**Comment by cjw85** [comment]
There are a few niggles with tensorflow 1.14 for which we would like to upgrade, but currently no sufficiently compelling reason for us to take the leap to 2.0.

Medaka already uses keras to build and save models, and to control the training workflow.

**Comment by cjw85** [comment]
We've had a quick look at upgrading to tf2.0, and ran in to some (possibly trivial) CUDA issues; sufficient for us to queue this work behind other priorities.

**Comment by nodrogluap** [comment]
FWIW I made the minor changes needed for TensorFlow 2.0 support (keras package renaming + eliminating cuDNNGRU as it's now implicitly selected from GRU at runtime if possible). I think there might be a change in serialization of the model between versions, because it runs fine but the consensus is utter rubbish.

**Comment by cjw85** [comment]
Upgrading medaka to TF2.2 is currently being worked on.

**Comment by cjw85** [comment]
We have just released v1.1.0 which uses Tensorflow 2.2
