### ISSUE TITLE
How strict are the version requirements for dependencies?

### ISSUE THREAD

**Issue by boegel** [nanoporetech/medaka#124]
While looking into adding support to [EasyBuild](https://easybuilders.github.io/easybuild/) for installling `medaka` 0.11.3, I noticed some rather strict version requirements for the required Python packages, specified in https://github.com/nanoporetech/medaka/blob/master/requirements.txt.

In particular:

* `tensorflow==1.14.0`: Is this version strictly needed, or will 1.13.x also work?
  * #116 tells me TensorFlow 1.15 will not work, is that still the case?
  * #107 tells me TensorFlow 2.0 will not work (fine, I can live with this)

* `numpy==1.16.1`: Is that only there so Travis will be happy w.r.t. the required `numpy` version for TensorFlow as the comment suggests? If so, which `numpy` version is sufficient?

* `h5py==2.7.1`: Is this still valid? The comment suggests this is because of `keras`, which is no longer listed as a requirement (which is confirmed by https://github.com/nanoporetech/medaka/issues/117#issuecomment-567084311)

* `pysam==0.15.2`: Is 0.15.2 strictly required, even if I install `pysam` myself from source (the "broken wheels" comment is probably irrelevant then?)

(note: in addition, #123 tells me I should stick to Python <= 3.6, I'll ping for more info on that in that specific issue)

The reason I'm asking is because we have "generations" of build recipes (so called easyconfig files) in EasyBuild, where we gradually update to the latest versions of the software we support.

Adding support for `medaka` is complicated because of the (perceived?) need that it requires somewhat old versions of specific dependencies, so I'm hoping to clarify that a bit to see which corners I'll need to cut.

If I stick to the `2018b` generation of easyconfigs we have, which seems to be my best bet for now, I'd have to stick to:
* Python 3.6.6 (+ numpy 1.15.0)
* TensorFlow 1.13.1
* h5py 2.8.0

Would going forward with that work for `medaka` 0.11.3?

**Comment by cjw85** [comment]
Hi @boegel,

To explain our philosophy here first, our dependencies are pinned fairly tightly in order to ensure that we can provide a working setup for most users. Our preferred packaging and distribution is based around python's (now fairly mature) manylinux binary wheels, and use of a virtual environment for isolation. We find this works well for most users, though we also provide a conda package through the bioconda channel as something commonly used by the community.

The precise pinnings in `requirements.txt` have grown organically from incompatibilities we have found through development. Because we typically recommend virtual environments or conda for isolation this isn't limiting, and we have not expended effort in testing the grid of dependency versions.

Turning to your questions, I can provide loose guidance.

    tensorflow==1.14.0: Is this version strictly needed, or will 1.13.x also work?

I do not believe we ever used 1.13.x with medaka, we upgraded from 1.12.x to 1.14.0 as a stepping stone to using 2.0 as 1.14 contains a mature keras implementation, such that we could drop use of the standalone `keras` requirement. I cannot really advise whether or not 1.13.x will work.

    #116 tells me TensorFlow 1.15 will not work, is that still the case?
    #107 tells me TensorFlow 2.0 will not work (fine, I can live with this)

We have done a little bit of work here to upgrade to 1.15. There are reports of people doing this successfully; we have not internally managed this in a reproducible way, this may simply be due to a change in CUDA version requirements.

    numpy==1.16.1: Is that only there so Travis will be happy w.r.t. the required numpy version for TensorFlow as the comment suggests? If so, which numpy version is sufficient?

We have not recently tested medaka with other versions of numpy. It was a while since we pinned this. I think I am right in saying this was the most recent version at the time of the pinning. It is likely that newer versions work equally fine.

    h5py==2.7.1: Is this still valid? The comment suggests this is because of keras, which is no longer listed as a requirement (which is confirmed by #117 (comment))

standalone keras is not a requirement but we still use the keras API within tensorflow. The comment is valid, but its only an issue during training not general medaka use. It may be possible that newer versions can be used if using medaka only for inference.

    pysam==0.15.2: Is 0.15.2 strictly required, even if I install pysam myself from source (the "broken wheels" comment is probably irrelevant then?)

   You are correct, this pinning is due to wishing to avoid building pysam from source when medaka is installed via `pip` or from the source code. I would warn however that we have had repeated issues with pysam not maintaining a stable API and have had to amend medaka to accommodate.

**Comment by boegel** [comment]
@cjw85 Thanks for the info, this is very helpful.

What's the best way to check whether the `medaka` installation I end up with is fully working as expected?

**Comment by cjw85** [comment]
There is a relatively comprehensive set of unit and regression tests within the project using pytest. We run these during development and within our continuous integration pipelines using `make test`. You might want to just look at the `makefile` for want it is running.

**Comment by boegel** [comment]
I tested the installation I obtained with EasyBuild using `pytest medaka` (which is basically what `make test` does, except that this also downloads & installs its own SAMtools, which I want to avoid), and all 189 tests passed (no errors failures, and handful of warnings about triggering deprecated stuff look very minor).

For future reference, here's the complete environment I used:

* Python 3.6.6
* cffi 1.11.5
* numpy 1.15.0
* TensorFlow 1.13.1
* h5py 2.8.0
* Pysam 0.15.1
* SAMtools 1.9
* HTSlib 1.9 (for tabix, bgzip)
* minimap 2.12
* Biopython 1.72
* intervaltree 3.0.2
* mappy 2.17
* ont-fast5-api 2.0.1
* parasail 1.1.19
* whatshap 0.18
* Racon 1.4.10
* spoa 3.0.1

(see also https://github.com/easybuilders/easybuild-easyconfigs/pull/9705)

Based on the passing tests, I'll conclude that this is working, so I'll close this issue...
