### ISSUE TITLE
model r941_min_fast_g303 missing

### ISSUE THREAD

**Issue by DewBudd** [nanoporetech/medaka#146]
I updated medaka and now the  model I have been using is no longer available. Is there a new model I should be using or a way to get the previous r941_min_fast_g303 model file?

**Comment by cjw85** [comment]
Hi @DewBudd,

We removed some older models in the latest release due to some constraints on package sizes for [pypi](https://pypi.org/). We intend to provide a tool in future to download older models; for now you can find the model you mentioned here: [r941_min_fast_g303_model.hdf](https://github.com/nanoporetech/medaka/blob/62846c2de1885e8cb8c6230fe7ec522eb0c4afd4/medaka/data/r941_min_fast_g303_model.hdf5?raw=true). This can be used with medaka by specifying the path the file as the model argument to the command line programs.
