### ISSUE TITLE
Issue using -v option

### ISSUE THREAD

**Issue by SAMtoBAM** [nanoporetech/medaka#148]
Hi there, 
I just updated medaka in order to use the new -v option with medaka consensus
I ran medaka again without '-v' and it works fine, 
However, when I add the -v option I get this error:

[02:11:17 - Variants] Building interval tree
Traceback (most recent call last):
  File "/usr/local/bin/medaka", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/medaka/medaka.py", line 601, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/medaka/variant.py", line 295, in samples_to_bed
    tree.merge_overlaps(strict=False)
TypeError: merge_overlaps() got an unexpected keyword argument 'strict'

No GPU
Installed using pip3

To note, 
The plan was to use the vcf then to create a consensus without breaking the contigs (mentioned in another post: https://github.com/nanoporetech/medaka/issues/131), however, what I find is that using the -v option, although the run seems to stop prematurely, I still get an assembly which looks the same as the bcftools consensus assembly I can generate with the vcf file...is this normal? I thought the -v option was to only generate a vcf additionally

Thanks

**Comment by mwykes** [comment]
Hi @SAMtoBAM, thanks for trying the new -v option. 

In addition to generating a consensus sequence from the vcf with bcftools consensus, the -v option generates a bed file showing which regions of the draft were polished (and hence which regions were not due to e.g. gaps in coverage). The error is to do with the part of the code creating the bed file. As such, your consensus sequence will have been created, but your bed file will not. 

Can you tell me what version of intervaltree you have installed (`pip freeze | grep intervaltree`) ? 

The code has been tested with the latest version 3.0.2.

If you don't have that, can you try installing it (`pip install intervaltree==3.0.2`)?

**Comment by SAMtoBAM** [comment]
Oh brilliant, so it already does the next step with bcftools consensus!
So just to check then, this option should make all the same modifications just without breaking contigs?

I just checked with and my intervaltree version was 2.1.0
I have updated it to 3.0.2 and re-run medaka consensus with '-v'
Worked perfectly
