### ISSUE TITLE
model for guppy v3.2.6

### ISSUE THREAD

**Issue by nilay-p** [nanoporetech/medaka#153]
Hi,
Would it be possible to provide a consensus model suitable for MinION-guppy v3.2.6, please?
Best,
Nilay

**Comment by cjw85** [comment]
Hi @nilay-p 

We removed some older models in the latest release due to some constraints on package sizes for pypi. The next release of medaka will include functionality to automatically download older models; for now you can find an appropriate model here: [r941_min_fast_g303_model.hdf](https://github.com/nanoporetech/medaka/blob/62846c2de1885e8cb8c6230fe7ec522eb0c4afd4/medaka/data/r941_min_fast_g303_model.hdf5?raw=true). This can be used with medaka by specifying the path the file as the model argument to the command line programs.

https://github.com/nanoporetech/medaka/issues/146

**Comment by nilay-p** [comment]
@cjw85 thanks for your quick reply.
