### ISSUE TITLE
correcting >1 kb indels

### ISSUE THREAD

**Issue by dcopetti** [nanoporetech/medaka#175]
Hello,

I wonder if Medaka is able to correct larger (>1 kb?) indels on a polished (QV >30) assembly. those indes stem from negative gaps in the scaffolds obtained anchoring the polished contigs to a Bionano map, or little gaps (<1 kb) still to be closed.
Would it work?
Thanks,
Dario

**Comment by cjw85** [comment]
If you have reads that span these gaps, then it is possible that medaka can insert the missing sequence. However this would rely on being able to align the reads across the gap in a single alignment since medaka only uses primary alignments from an input bam file.

So the answer to you question is it might work, but it is not something that medaka takes great care to achieve.

**Comment by dcopetti** [comment]
cool, I'll give it a try then!
