### ISSUE TITLE
unexpected VCF annotate results

### ISSUE THREAD

**Issue by will-rowe** [nanoporetech/medaka#192]
**Describe the bug**
Currently testing `medaka tools annotate` and am receiving unexpected results for `DP` (Depth of reads at pos) when dealing with INDELs.

**Logging**
Please attach any relevant logging messages.

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method: conda (v1.0.3)
 - OS: osx
 - GPU model: No GPU

**Additional context**
For example:
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SAMPLE
MN908947.3	29749	.	ACGATCGAGTG	A	242.676	PASS	AR=8,3;DP=10;DPS=4,6;DPSP=200;SC=1193,1214,1397,1445;SR=19,18,73,79	GT:GQ	1:243
```
Depth at this position should be ~200, as confirmed by looking at the BAM and as is reported by longshot, nanopolish etc. for the same sample.
When provided with a pad of 1, the `Depth of reads spanning pos +-1` is the expected value.

Looking at [the code](https://github.com/nanoporetech/medaka/blob/b5fc63fde161e5a73315dd5348bd9113bfbbbcc5/medaka/vcf.py#L1079-L1080), this might be a known bug already?

**Comment by will-rowe** [comment]
# Data for reproducing

This was picked up during CI for the [artic pipeline](https://github.com/artic-network/fieldbioinformatics/tree/master/artic)

MT007544 data available [here](https://raw.githubusercontent.com/artic-network/fieldbioinformatics/master/test-data/MT007544/MT007544.fastq)

Expected var info is [here](https://github.com/artic-network/fieldbioinformatics/blob/master/artic/minion_validator.py#L99)

**Comment by NatPRoach** [comment]
Hello, I ran into what I believe is the same issue recently. It seems as though the `DP` coverage value is lower (often substantially lower) than the `DPSP` when dealing with indels. This is not expected behavior correct? My expectation is that if a read spans a region around a base in the reference in the `DPSP` count that it would also count as covering that base in the `DP` count. Is that not the intended interpretation of the `DP` and `DPSP` info fields? Wanted to make sure I'm interpreting these fields correctly. Would appreciate any help / clarification you can provide. Thanks!

**Comment by cjw85** [comment]
I have a feeling this issue was resolved. Please reopen if further problems arise.
