### ISSUE TITLE
VCF annotations

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#263]
**Describe the bug**
1 - `medaka_haploid_variant` does not seem to provide any annotations (QUAL and DP are the ones most important to me). Is there a way to get it to provide this?

2 - I also tried using `medaka tools annotate consensus_to_ref.vcf genome.fna consensus_to_ref.bam medakaannout.vcf` but it keeps failing with the below log. I am not sure if the consensus_to_ref.vcf and consensus_to_ref.bam are the files I should be using for this purpose. medaka_haploid_variant seems to create many files (calls_to_draft.bam and consensus_probs.hdf being the biggest). My goal is to get a vcf to then use with snpEff - other than consensus_to_ref.vcf none of the other seem useful for my purposes - is there a reason to keep the other files? Would you recommend any other modifications to my steps? The consensus_to_ref.vcf file seems fine except the lack of annotations.

> [00:08:04 - Annotate vcf] Getting chrom coordinates
> [00:08:09 - Annotate vcf] Chunking regions
> Traceback (most recent call last):
>   File "/anaconda3/bin/medaka", line 11, in <module>
>     sys.exit(main())
>   File "/anaconda3/lib/python3.8/site-packages/medaka/medaka.py", line 684, in main
>     args.func(args)
>   File "/anaconda3/lib/python3.8/site-packages/medaka/vcf.py", line 1143, in annotate_vcf_n_reads
>     if region_chunks.size else chunks
> AttributeError: 'list' object has no attribute 'size'

3 - I am also curious if you would recommend custom certain settings (chunk size, etc) for running medaka_haploid_variant for a yeast genome (total size ~12Mb, 16 chromosomes of length 230k-1.5Mb as well as an 85k mitochondria)

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method from conda
 - OS: Ubuntu 20.04

**Comment by cjw85** [comment]
v1.2.4 released yesterday on PyPI fixes the error in `medaka annotate`; a conda package for this release is currently held up with build issues (https://github.com/bioconda/bioconda-recipes/pull/27176).

All the options in medaka are configured to have sensible default values. They should for the most part be left untouched.

If you are running medaka without a GPU, you may wish to look at the [Improving parallelism](https://nanoporetech.github.io/medaka/installation.html#improving-parallelism) section of the documention since medaka otherwise does not provide parallelism over contigs (for the case of GPU use, medaka is limited largely by HTSlib BAM parsing speed). For example you can run `medaka_haploid_variant` independently on each chromosome to improve parallelism.

**Comment by jpn2021** [comment]
Thank you. Would you consider adding that as a feature to have it detect a set number of regions or chromosomes and parallelize itself?

**Comment by jpn2021** [comment]
The new version 1.2.5 seems to have fixed `medaka tools annotate` - thank you! Would it make sense to run the medaka tools annotate program using consensus_to_ref.vcf and calls_to_draft.bam? Is there a different bam file that would be better? Is there a way to use consensus_probs.hdf?

After running the program it seems to annotate only DP and DPS (no QUAL or any other annotations). Also in the vcf file (and the consensus_to_ref.vcf file) seems like many of the variants have the same same REF and ALT base - why would it consider that a variant? Is this because of some haploid/diploid issue?
