### ISSUE TITLE
Problem with multithreads in medaka_vairant

### ISSUE THREAD

**Issue by huangnengCSU** [nanoporetech/medaka#272]
**Describe the bug**
I ran medaka to call small indel and SNPs but the CPU utilization is very low. Here is my command:
```
medaka_variant -i GM24149_40X.sort.bam -f GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna -o medaka_call/ -t 40
```
The cpu information is as follows:
![image](https://user-images.githubusercontent.com/28866823/110718108-524c0480-8245-11eb-9644-b6be39fabf56.png)

**Logging**
Please attach any relevant logging messages.

**Environment (No GPU):**
 - Installation method: from github source
 - OS: Ubuntu 20.04

**Comment by cjw85** [comment]
Hi @huangnengCSU,

This is the expected behaviour. The medaka steps in the `medaka_variant` script should used little CPU resource. We've unfortunately not had the time to devote to making the workflow scale to whole genome processing. However the whole process is trivially parallelized over genomic regions, `medaka_variant` accepts `-r` option which is of the form: `"chr1:1-10000000"`.

10Mb is roughly an appropriate size and will not affect phasing too much (though phase blocks can exceed 10Mb). But you may wish to rephase after having merged all VCFs from the independent calculations.
