### ISSUE TITLE
Contigs merged/removed when polishing?

### ISSUE THREAD

**Issue by gf777** [nanoporetech/medaka#292]
Hi,

I am running the latest medaka_consensus. I don't understand why if I start with say 600 contigs, the consensus.fasta file only contains say 400. The size of the two assemblies are comparable (about 1 Mbp difference relative to the size of a human genome) yet there is not indication in contig headers of contigs being merged or similar. The total size of the missing contigs is aboyt 4 Mbp. Are contigs without read support removed without notice? Is there a way to prevent this?

Thanks

**Comment by cjw85** [comment]
Guilio,

In future please provide all information requested in the issue template. Medaka is very often iterated quickly and bugs fixed, we at least need to know the version of medaka that you are running.

In this instance I believe there is an oversight in the code. If sequence is missing medaka's consensus output from part of a contig through lack of coverage after the reads are aligned, medaka will by default fill in the sequence from the draft. However if the entirety of a contig lacks coverage it will be dropped from medaka's output, rather than carried across verbatim. We will look at amending this behaviour.

**Comment by gf777** [comment]
Hi, sure sorry for the ambiguity, I am using medaka 1.2.6. I think amending the behavior is good, because there could be (good) reasons for lack of coverage. Best

**Comment by cjw85** [comment]
This was fixed in medaka v1.3.3
