### ISSUE TITLE
able to use symlinks with medaka_variant?

### ISSUE THREAD

**Issue by RichardCorbett** [nanoporetech/medaka#296]
When I run medaka_variant using symlinks as below I see errors reporting that the file is unreachable
`ls
D74501.sorted.bam -> /projects/rcorbettprj2/2019FFPE/scratch/promethion/tmp/work/6f/eb19a4b1dadeb19d372cb7223ced11/D74501.sorted.bam
D74501.sorted.bam.bai -> /projects/rcorbettprj2/2019FFPE/scratch/promethion/tmp/work/52/e147bdb44eace529e0f2d6393da218/D74501.sorted.bam.bai
hg19a_phage_lambda.fa -> /projects/alignment_references/Homo_sapiens/hg19a_phage_lambda/genome/fasta/hg19a_phage_lambda.fa
hg19a_phage_lambda.fa.fai -> /projects/rcorbettprj2/2019FFPE/scratch/promethion/tmp/work/49/8468f51754750925bd5d5721247435/hg19a_phage_lambda.fa.fai
`

When I run medaka_variant I get this error:
`medaka-1.3.2/bin/medaka_variant -f hg19a_phage_lambda.fa         -i D74501.sorted.bam         -t 8         -s r941_prom_snp_g360         -m r941_prom_variant_g360         -o D74501_1         -P 0         -l         -r 1
Could not find file /projects/rcorbettprj2/2019FFPE/scratch/promethion/tmp/work/6f/eb19a4b1dadeb19d372cb7223ced11/D74501.sorted.bam.bai, exiting.
`

Note that above, the .bai and .bam file are in different folders but symlinked to be in the same folder, which is where the medaka command is running.  This is due to the way our nextflow workflow is operating.  Files are created in different folders and then symlinked together into 1 folder for any analysis where they are needed.

If I copy the .bam and .bai file into 1 folder medaka_variant runs without errors.  Is there a way to use the links as they are set up above without having to copy the .bam and .bai to the same folder?

**Version 1.3.2.**

**Comment by cjw85** [comment]
The issue here is that during parsing the command-line arguments, the program resolves the BAM input to the real absolute path of the file, this is then used throughout the rest of the execution. Since many (all?) the programs that script executes assume that the index file lives alongside it's corresponding BAM, `medaka_variant` checks for the presence of the implied location of the index file from the BAM location. If it did not perform that check something else (`medaka`, `whatshap`, `samtools` come to mind through their use of htslib) would fail.

In summary the program as written requires the BAM and BAI to live alongside each other (as real files).

To avoid your issue, I might suggest either take a copy of `medaka_variant` into your nextflow project and remove the resolution of relative symlinks to real absolute paths. Alternatively create the index file in the same nextflow process as the BAM, so something like:

```
process alignment {
    inputs:
        ...
    outputs:
        tuple path("mybam.bam"), path("myindex.bam.bai)
    script:
    """
    minimap2 ... | samtools sort > mybam.bam
    samtools index mybam.bam
    """
}
```

The `medaka_variant` script was never intended to be used in routine analysis, but merely to show the process. It doesn't implement any advanced parallelism, though the whole process can be applied on isolated genomic regions, with approximately identical results. The workflow is currently being implemented as a nextflow workflow, but I cannot give a timeline on when that will be available.

**Comment by cjw85** [comment]
Closed due to inactivity.
