### ISSUE TITLE
Weighting of variant calling quality scores by depth

### ISSUE THREAD

**Issue by W-L** [nanoporetech/medaka#316]
Hi,
This is more of a question than a feature request. I am trying to compare variant calling quality scores (using `medaka_haploid_variant`) from multiple samples of the same input material and noticed a slightly counterintuitive aspect of the quality scores, that is the lack of correlation between quality scores and coverage depth. As an example, considering the same SNV position in two samples (where * denotes the reference base) we might observe:
```
      Sample A                         Sample B
      counts       probabilities       counts         probabilities
-     2            4.5214365e-06       1              1.5814047e-06
A*    2            2.3729615e-05       0              4.4658286e-06
C     0            1.3721217e-06       0              1.0916673e-06
G     26           9.9996936e-01       12             9.9999022e-01
T     0            1.0323455e-06       0              2.7932053e-06 

total coverage depth:
      30                               13

quality score:
      45.137                           50.099

``` 
I saw that the counts of pileups are normalized by the total coverage at a position (`feature_array = counts / np.maximum(1, depth).reshape((-1, 1))`), which explains the higher quality score for Sample B. I feel like the confidence we have in a variant call should be higher if we have observed more evidence at a position, though. Given that at higher coverage we expect more errors at a position this normalization seems to bias against higher depth, especially compared to the extreme case of observing only 1 or 2 reads at a position, which is of course not a real problem when filtering by depth & quality. 
The `CountsFeatureEncoder` class seems to have the option of not performing this normalization.
https://github.com/nanoporetech/medaka/blob/3c919abf1e852b5bc8f2ff1c24abcad1059357c2/medaka/features.py#L473-L488 
But I'm not sure whether this can actually be used to skip the normalization step and use raw counts? I assume the RNN expects a matrix with values in [0,1]? If that's not an option, do you maybe have any other advise how to compare confidence in variant calls? Using coverage depth alone seems a bit unsatisfactory

Thank you so much for your help, I really appreciate it!
Lukas

**Comment by cjw85** [comment]
Hi,

You are correct in observing that the base counts that are input in the RNN are normalized to to total depth. Turning this normalization off is unlikely to lead to meaningful results. I would not try to draw any inference about the quality of a call from the distribution of the input counts: if that were possible in the general case then its very likely that medaka could use methods simpler (an more amenable to interpretation) than its RNN. Having said that I'm unsure what you mean by:

> Given that at higher coverage we expect more errors at a position this normalization seems to bias against higher depth

since we also observe more correct bases.

These issues aside, I can offer two observations:

- We know in from our work on diploid calling (which we actually perform having approximately solved the phasing problem) that the quality scores that medaka outputs are roughly correlated with empirical error of the calls, at least to the point that false positive calls can be filtered with a simple threshold to improve the f1-score.
- It is known in the literature (I can't recall the papers immediately but fairly comical examples can be found on the internet) that RNN and similar models can be irrationally confident in their predictions. The scores output from medaka are formed directly from the network outputs with no other information, so you can expect the confidences of incorrect calls to sometimes indicate high confidence.

There's certainly some work to do in this area. One thing we have wanted to do, but never found the time, is apply a secondary model on top of the network outputs (perhaps taking information concerning the reference sequence) to produce more informative scores.

For you own purposes do you have evidence that the scores in the VCFs are not giving an accurate indication of which calls to trust and which to be skeptical of?

**Comment by W-L** [comment]
Thank you for the insightful answer! It's very helpful in order for me to understand what the scores can and cannot be used for.

> For you own purposes do you have evidence that the scores in the VCFs are not giving an accurate indication of which calls to trust and which to be skeptical of?

I don't have any concerns about the scores leading to inaccurate results or calls that we can not trust. What I was trying to do was to use the scores in a quantitative way to compare variant calls from samples with different coverage depth. I.e. do we get a higher score ("higher confidence") for a variant if we sample more coverage at that site? But given the normalisation it became clear why I could not see any correlation between the coverage depth and the quality score 

![fig_cov_qual_boxes](https://user-images.githubusercontent.com/16755298/127463099-7a34ab90-ce65-4391-9a15-e09371930f1b.png)

I understand now that the scores are not necessarily intended to be used that way, and that we perhaps need to find another way to express the difference in confidence about variant calls when sampling at a higher depth.
