### ISSUE TITLE
Is tensorflow==2.2.2 still a fixed requirement?

### ISSUE THREAD

**Issue by sassy-crick** [nanoporetech/medaka#323]
This program is used widely in the community I am doing the technical support.
As there is a new version of Tensorflow out (2.4.x) and in light of the latest nVidia A100 cards, 
I was wondering if it is still necessary to pin Tensorflow to version 2.2.2 or is that no longer a strict 
requirement? 
The motivation for this question is:
On modern HPC installations often software management tools are used and thus it is 
not really desirable to have two different versions of the same program, here Tensorflow, installed using
the same toolchain. Thus, it would be good to look into that requirement again and maybe loose it to
tensorflow>=2.2.2 for example, if possible. 
Thanks.

**Comment by cjw85** [comment]
We have been caught out multiple times in the past by subtle changes in behaviour, performance, and bugs when updating tensorflow or allowing a looser version specification. We have done some minimal testing with tensorflow 2.4, but not sufficient to make the change.

There are various methods available to handle conflicting versions of software from virtual and conda environments to module systems and containers.

The precompiled tensorflow packages available on PyPI and conda are linked against specific versions of CUDA and cuDNN. It is of course possible to compile your own tensorflow package linked to the version of these libraries of your choosing. But this is not something we have tested.

If docker is an option for you, there is a GPU enabled medaka container available from dockerhub under the ontresearch namespace.

**Comment by Flamefire** [comment]
May I suggest not fixing the patch version of TF then and use instead a specifier such as `~= 2.2.2`? E.g. currently TF 2.2.3 is the latest 2.2 release and contains a multitude of security related fixes. TF (usually?) doesn't change it's interface between patch versions, so leaving that open is appropriate.
See https://stackoverflow.com/questions/39590187/in-requirements-txt-what-does-tilde-equals-mean and https://github.com/tensorflow/tensorflow/releases/tag/v2.2.3

**Comment by boegel** [comment]
@cjw85 Is there a test suite for `medaka` that can help us asses the impact of using a different TensorFlow version, i.e. how hard things are broken if/when we do?

**Comment by cjw85** [comment]
@Flamefire The change you have suggested has been applied in our development branch and will appear in the next release. Our internal testing is now running against this.

@boegel The full source tree contains unit tests on most of the API-like code in medaka. We don't provide high-level integration tests, which for the purposes of testing tensorflow compatibility would be tantamount to running `medaka consensus` on a suitable BAM file of your choosing.

I note also the `"s/h5py<3.0.0/h5py/"` line in your linked build script. I would consider this at risk also. We pin these things for good reason after coming across issues which we make best efforts to mitigate but do not always have the capacity to resolve in a complete dependency agnostic manner.

You are welcome to deviate from the code we provide but such use is completely unsupported by us. We provide and maintain packages on PyPI and bioconda. These are intended for use in standalone shell environments, which is what we recommend and support. The container image on dockerhub is provided to ensure a straightforward route to using medaka with GPUs (where the larger issue of GPU drivers and Nvidia libraries is a little nightmarish otherwise).
