### ISSUE TITLE
HDF5: infinite loop closing library

### ISSUE THREAD

**Issue by jpn2021** [nanoporetech/medaka#335]
**Describe the bug**
At the end of running medaka consensus I get an infinite loop error as follows (including some context). I get an hdf file but it does not seem usable for downstream variant calling. 

> [11:04:36 - PWorker] Batches in cache: 17.
> [11:04:42 - PWorker] Batches in cache: 12.
> [11:04:42 - PWorker] 20.7% Done (0.0/0.1 Mbases) in 11.9s
> [11:04:52 - PWorker] Batches in cache: 9.
> [11:04:57 - PWorker] Batches in cache: 7.
> [11:04:57 - PWorker] 49.9% Done (0.0/0.1 Mbases) in 26.3s
> [11:05:08 - PWorker] Batches in cache: 5.
> [11:05:08 - PWorker] 68.1% Done (0.0/0.1 Mbases) in 37.5s
> [11:05:16 - PWorker] Batches in cache: 1.
> [11:05:17 - PWorker] Processed 18 batches
> [11:05:17 - PWorker] All done, 0 remainder regions.
> [11:05:17 - Predict] Finished processing all regions.
> HDF5: infinite loop closing library
>L,T_top,P,P,Z,FD,PL,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E

I found I already had to reduce the batch_size to 50 and bam_chunk to 10000 to avoid OOM errors. Here is the code:

`medaka consensus --model r941_min_hac_variant_g507 ./OUTPUTS/$dir.bam ./OUTPUTS/$dir.hdf --bam_chunk 10000 --batch_size 50`

**Environment**
 - Installation method: _conda_
 - OS: _WSL2 Ubuntu 20.04.3_
 - medaka version: _1.4.4_
 - GPU model: _RTX 2060_
 - Nvidia driver version: _472.12_
 - CUDA version: _11.4_

**Comment by cjw85** [comment]
Hi @jpn2021,

My first suspicion here is that something about using WSL2 is causing this error. The error you have reported is not something we have ever observed. Is the error reproduceable, does it occur across many runs of `medaka consensus` on the same dataset?

I'm afraid this isn't something that I can promise a resolution on immediately since we have no experience of using medaka under Windows Subsystem for Linux. You might like to ask within the Nanopore Community forum as I know some other users have successfully used medaka under WSL2.

**Comment by cjw85** [comment]
Closing as stale.
