### ISSUE TITLE
medaka v1.5.0 variants calling commands.

### ISSUE THREAD

**Issue by Huanle** [nanoporetech/medaka#353]
Hi There,

I just started playing with medaka and am a bit confused with the proper commands for variants calling. 
I have tried the following command lines and managed to get some results. 
```
export TF_FORCE_GPU_ALLOW_GROWTH=true
medaka_consensus -i all.FQ -d ~/lhl/proj/AS/human_/Refs/ucsc/hg38.fa -t 40 -m r941_min_sup_g507 -o medaka_consensus                                         
medaka variant  medaka.consensus/consensus.fasta medaka.consensus/consensus_probs.hdf var.vcf  
```
But i noticed there is a `consensus` sub-command that i do not know its difference from *medaka_consensus*. Can you please help me to tell the difference?

**Comment by cjw85** [comment]
Hi @Huanle,

medaka is designed following the Unix principle of a set of composable tools that individually perform one task. The subcommands of the `medaka` program are these tools.

For the convenience of users we provide also shell scripts to automate two workflows:
1) `medaka_consensus` -- creating a consensus sequence from reads and an draft sequence
2) `medaka_haploid_variant` -- creating variant calls for haploid samples

Advanced users can inspect the contents of this shell scripts to see how the individual composable tools are used to perform different tasks. We no longer provide diploid calling in medaka because the workflow we historically used for this has been surpassed in accuracy by other tools, our current recommendation is to use [Clair3](https://github.com/HKU-BAL/Clair3) for this task.

**Comment by Huanle** [comment]
Hi @cjw85 ,
thanks a lot for your clarification. It makes sense to me. 
Best,
Huanle
