### ISSUE TITLE
Specify if racon pre-polishing is still recommended

### ISSUE THREAD

**Issue by RaverJay** [nanoporetech/medaka#354]
Hi,

previously there was this page with details about Medaka and how to run it, but the link is dead: https://nanoporetech.github.io/medaka/draft_origin.html
(It can still be found on the wayback machine of internet archive: https://web.archive.org/web/20211021202900/https://nanoporetech.github.io/medaka/draft_origin.html)

On there it said that Medaka models are trained on Flye assemblies that have been processed with one round of racon (with parameters `racon -m 8 -x -6 -g -8 -w 500`)

The readme is a little vague, only mentioning Flye - should racon be skipped?

Thanks!

**Comment by cjw85** [comment]
We've removed the github.io site because it was becoming a burden to maintain. All the important content now sits in the README to this repository.

Contemporary medaka consensus models are trained to act upon the output of the Flye assembly directly, the previous advice to use racon is no longer valid.

**Comment by cjw85** [comment]
I've updated the README to note that the historical advice is not correct for current use. This will appear the next time we make a release of the software.
