### ISSUE TITLE
medaka_haploid_variant model selection and quality filter

### ISSUE THREAD

**Issue by katefgit** [nanoporetech/medaka#402]
I am running ```medaka_haploid_variant``` to compare R.10.4 reads (basecalling model  ```r10.4.1_e8.2_260bps_hac```) to reference using either  ``` -m r1041_e82_260bps_hac_g632 ``` or  ``` -m r1041_e82_260bps_hac_variant_g632 ``` and I get different results. Is it true I should use the second one, and the first one for the  ``` medaka_consensus ``` and does it makes sense that I get usually less SNPs with the latter and that the ``` QUAL ``` scores don't fit? 

<img width="680" alt="image" src="https://user-images.githubusercontent.com/74652982/206700400-17d415bd-9938-440f-af21-97b265d41c20.png">

Moreover, could you advice on how/if one can/should filter the SNP based on the ``` QUAL ``` scores?

**Comment by cjw85** [comment]
Yes, the first model is for consensus calling where the reads are assumed to be aligned to an uncorrected draft assembly; the second model is for variant calling where the reads are assumed to be aligned to a near perfect reference sequence.

I'm unsure what you mean by the `QUAL` scores not fitting.

**Comment by katefgit** [comment]
Thanks for the answer. By that I mean that for the same position the QUAL score when using the -m r1041_e82_260bps_hac_g632 is for e.g. 0.8 and when using the -m r1041_e82_260bps_hac_variant_g632 is 23.55. Does this make sense?
Also, do you know if there is any rule on how I can filter out SNP based on the QUAL score? E.g. disregard the SNP with a QUAL < 10 or something like that? I am thinking to look at the alignment and find out for each position what is the %frequency of the SNP, but I was also trying to figure out if there is an "easier" way. I am thinking that 24 SNP using the hac and R10 is still quite high and I can see that all the SNP are found on homopolymer regions.

**Comment by katefgit** [comment]
> Yes, the first model is for consensus calling where the reads are assumed to be aligned to an uncorrected draft assembly; the second model is for variant calling where the reads are assumed to be aligned to a near perfect reference sequence.
> 
> I'm unsure what you mean by the `QUAL` scores not fitting.

> Thanks for the answer. By that I mean that for the same position the QUAL score when using the -m r1041_e82_260bps_hac_g632 is for e.g. 0.8 and when using the -m r1041_e82_260bps_hac_variant_g632 is 23.55. Does this make sense? Also, do you know if there is any rule on how I can filter out SNP based on the QUAL score? E.g. disregard the SNP with a QUAL < 10 or something like that? I am thinking to look at the alignment and find out for each position what is the %frequency of the SNP, but I was also trying to figure out if there is an "easier" way. I am thinking that 24 SNP using the hac and R10 is still quite high and I can see that all the SNP are found on homopolymer regions.

**Comment by cjw85** [comment]
There's no reason for the two sets of `QUAL`s to be comparable: the models assume different things about the data.

The QUAL field is a measure of the probability that the call is correct. All the variants written to the output are the most probable base at each locus, according to the model. Now of course the model is not perfect and can be wrong. The only reason to filter a variant from the VCF is if you have access to prior knowledge that the model does not. I cannot say what knowledge you have about your own samples in order to do this but it might include things such as population frequencies of  variants. For example: if the population frequency of a variant is low and the QUAL listed in the VCF is also low, that might be taken as evidence that the variant is a false positive.

One area in which this gets more subtle is that knowledge about the properties of the error profile of medaka models can be used as such prior knowledge to augment the calls. The archetypal example of this is variants called in homopolymer regions: any such variants with a low QUAL should be questioned as they may be false positives.

Certainly one thing you should not do is simply look at the frequency of bases in reads at the position of a variant. To do so negates the use of medaka in the first place.

**Comment by katefgit** [comment]
ok, maybe I can explain a bit more why/how I am using medaka. I am working with bacterial strains and compare 2 strains, which based on HA are identical. Now I want to only sequence with ONT and compare the reads to HA and thus find out if they are identical. I could see many differences when using the R9, and less with R10, but still many SNP. Therefore, I was trying to find out if some of them could be "false positives" and filter them out based on the low QUAL. But it could also mean I need to improve my runs to get higher coverage or use "super accuracy" basecalling etc.

**Comment by cjw85** [comment]
I don't think there is any more further information and advice that I can provide here.
