### ISSUE TITLE
[Question] Seeking Guidance on Selecting Appropriate Model for ONT Sequencing

### ISSUE THREAD

**Issue by llk578496** [nanoporetech/medaka#506]
Dear @cjw85 ,

Since 2022, our laboratory has been utilizing Oxford Nanopore Technologies (ONT) sequencing for bacterial isolate sequencing. Last year, ONT has introduced Dorado as a new basecaller, which has undergone regular updates. However, we have encountered confusion when it comes to selecting an appropriate `--model` when working with data generated by different basecallers, basecaller versions, and flowcell types.

Our primary question is: What is the appropriate `--model` to use in the following conditions?

![Screenshot from 2024-04-28 19-18-58](https://github.com/nanoporetech/medaka/assets/78581211/50d8e40c-5b68-4e44-a96c-22e5d02ecbce)

The Version mentioned here corresponds to the version reported in the MinKNOW Run Report for each sequencing run.

We have diligently searched the documentation for guidance on choosing the appropriate `--model`, but we have been unable to find clear instructions. Therefore, we are seeking your assistance in resolving this matter.

Thank you in advance for your help and guidance.

Best regards,
Eddie

**Comment by cjw85** [comment]
Since version v1.11.2 medaka has had the ability to read basecaller model versions from fastq headers and choose the appropriate medaka model automatically. This is detailed in the README of this repository.

The versions you report are, I think, the versions of the basecall server within minknow. I don't believe there's an easy correspondence between these and the basecaller model. You would have to ask my technical support colleagues.

**Comment by llk578496** [comment]
Dear @cjw85 

Thank you very much for your prompt response! We shall try with the `--auto_model` option and contact the technical support. 

Thank you very much again for your help!

Best regards,
Eddie
