### ISSUE TITLE
update conda and docker

### ISSUE THREAD

**Issue by JWDebler** [nanoporetech/medaka#522]
Hi,

I just noticed that both medakas conda and docker repositories are out of date. Could you please update them, and make it part of releasing a new version to update both?
Conda is currently at 1.11.3 and docker at 1.12.0

Cheers

**Comment by cjw85** [comment]
We do not maintain the bioconda pacakges, you should file a issue over on their pages.

Our continuous deployment of docker containers has been amended recently, and is...cough...not very continuous it seems! I will look at fixing that.

**Comment by cjw85** [comment]
We've create prerelease conda packages for the next version of medaka. You should be able to install with:

```
conda create -n medaka -c conda-forge -c nanoporetech -c bioconda 'medaka==2.0.0a2'
```

**Comment by truong-phu-minh** [comment]
@cjw85 I can not install using your command line

**Comment by incoherentian** [comment]
@truong-phu-minh this resolved, downloaded, and built within maybe 5 minutes for me (albeit using mamba).

@cjw85 THANK YOU for carrying the ONT conda torch! As well as the py torch... I'll let myself out now.

**Comment by truong-phu-minh** [comment]
@incoherentian thanks for your comment. I have updated @cjw85 command line, but it returns this error:
Solving environment: \ warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
| warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package medaka-2.0.0a2-py310h8a0c2ca_0 requires htslib >=1.20, but none of the providers can be installed

Could not solve for environment specs
The following package could not be installed
└─ medaka 2.0.0a2  is not installable because it requires
   └─ htslib >=1.20 , which conflicts with any installable versions previously reported.

Is it compatible with the OSX-ARM64 platform? Please let me know.

**Comment by cjw85** [comment]
medaka v2.0.0 has now been released. We have not as yet released a docker image, though we'll do this in due course as collateral to integrating medaka v2.0.0 into EPI2ME workflows.
