### ISSUE TITLE
Mac issue installing v2.0.0

### ISSUE THREAD

**Issue by rmcolq** [nanoporetech/medaka#526]
**Describe the bug**
The latest release notes for medaka v2.0.0 say that it is compatible with MacOS. When I try to pip install medaka, the prerequisite for torch~=2.3 fails on Mac (can't be found in conda either). This makes the package uninstallable

**Logging**
```ERROR: Could not find a version that satisfies the requirement torch~=2.3 (from medaka) (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2)
ERROR: No matching distribution found for torch~=2.3```

**Environment (if you do not have a GPU, write No GPU):**
 - Installation method [from github source, pypi (pip install), conda]
 - OS: [e.g. Ubuntu 16.04] Mac M1 (possibly in emulator mode, but I to make this a dependancy that works on Mac intel too)
 - medaka version (can be found by running `medaka --version`) 2.0.0
 - GPU model No GPU
 - Nvidia driver version
 - CUDA version
 - cuDNN version

**Comment by cjw85** [comment]
pytorch most certainly is available on macOS for a variety of Python versions, see here:

https://pypi.org/project/torch/2.3.0/#files

Have you by chance fooled your macOS shell into thinking it is running under and x86 processor rather than an ARM one? I've seen people do this in the past with these sorts of consequences. (Or maybe you have an Intel-based device?).

**Comment by cjw85** [comment]
Closing through lack of response.
