### ISSUE TITLE
Medaka v0.8.0 tensorflow.keras.layers import error

### ISSUE THREAD

**Issue by macieksk** [nanoporetech/medaka#66]
Hi, with tensorflow '1.14.0' installed we've needed to apply the following patch for medaka v0.8.0 to work:

<pre>
diff --git a/medaka/models.py b/medaka/models.py
index bc6dba9..b0cbe6d 100644
--- a/medaka/models.py
+++ b/medaka/models.py
@@ -43,7 +43,7 @@ def build_legacy_model(chunk_size, feature_len, num_classes, gru_size=128):

     from tensorflow.keras.models import Sequential
     from tensorflow.keras.layers import Dense, GRU
-    from tensorflow.keras.layers.wrappers import Bidirectional
+    from tensorflow.keras.layers import Bidirectional

     model = Sequential()
</pre>

Python version is Python 3.5.7.

**Comment by cjw85** [comment]
Hi,

Thanks, it looks like we missed this in our tests since we only used more recent models. The above will fix model construction for the models `r941_flip213` and `r941_trans`. Other models should work already.

Can I ask which of these models you are using and why? There was a relatively small time window where Guppy 2.1.3 was current, and if you are using `r941_trans` to complement transducer basecalling I cannot recommend strongly enough to revisit the basecalling of your data with a current version of Guppy.

**Comment by macieksk** [comment]
We've been using `r941_flip213` since one of our validation samples is basecalled with flip-flop. We're currently rebasecalling it with `hac`, it will take some time before the whole validation process is updated. ... However, now I noticed on the main page that there are two flip-flop models:
> For guppy versions >=2.1.3 where the flip-flop algorithm has been used, users should select the highest numbered model equal to or less than the guppy version used for basecalling. There are two models here: `r941_flip213` and `r941_flip235`

Since our basecalling was on guppy2.3.7, it looks that we'd better be using `r941_flip235`. Thanks for explanations and bringing our attention to this!

**Comment by cjw85** [comment]
This has been resolved in [v0.8.1](https://github.com/nanoporetech/medaka/releases/tag/v0.8.1).
